name       : gamescope
version    : 3.11.51
release    : 7
source     :
    - git|https://github.com/Plagman/gamescope.git : 3.11.51
license    : BSD-2-Clause
component  : system.utils
summary    : gamescope - a micro wayland compositor useful for games
description: |
    gamescope is a micro wayland compositor useful for games. It creates a virtual environment for a game application to run in that helps solves various headaches such as resolution, alt-tabbing, mouse focusing issues etc. Gamescope also tries to remove as many unneccessary copies as it can and should provide better latency.
networking : yes
patterns   :
    - /*
builddeps  :
    - pkgconfig(libcap)
    - pkgconfig(libdrm)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(sdl2)
    - pkgconfig(stb)
    - pkgconfig(vulkan)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(x11)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(xkbcommon)
    - pkgconfig(xrender)
    - pkgconfig(xres)
    - pkgconfig(xtst)
    - pkgconfig(xwayland)
    - pkgconfig(xxf86vm)
    - pkgconfig(wlroots)
    - glslang-devel
    - vulkan-headers
setup      : |
    %meson_configure -Dforce_fallback_for=""
build      : |
    %ninja_build
install    : |
    %ninja_install
